theme: jekyll-theme-primer

baseurl: "/new-jekyll-blog"
title: Migraci√≥n del blog (R. Chavarria's blog)
description: Proud of developing software, proud of being an Engineer

show_downloads: false
google_analytics:

excerpt_separator: <!-- more -->
